# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e78e620f88872ed9aab38884d6b65c02695f77dd4e37a0768737fa3cb23cdf7564a3145a90ba618b9c0cf7cd9ce0bd6d142f0fb2ff5b27d80359e5c5e717308c

test:
  secret_key_base: 8387d5bf6360bbb8e9c3f514af51c1c2a92d0d0ef6e7e4e8601b4ce616f231e75f026b64e83d23fb6f3e421b699b2d95d0f12401ea30162e14016a3bb3cb0989

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 8387d5bf6360bbb8e9c3f514af51c1c2a92d0d0ef6e7e4e8601b4ce616f231e75f026b64e83d23fb6f3e421b699b2d95d0f12401ea30162e14016a3bb3cb0989
